version: '3.8'
services:
  bilgemongodb:
    image: mongo
    restart: always
    ports:
      - '27000:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root